# Generated by Django 6.0.7 on 2026-08-19 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('cultivation_information', models.TextField()),
                ('soil_types', models.CharField(help_text='Comma-separated soil types.', max_length=255)),
                ('seasons', models.CharField(help_text='Comma-separated seasons.', max_length=255)),
                ('locations', models.CharField(blank=True, help_text='Optional comma-separated locations.', max_length=255)),
            ],
            options={
                'verbose_name': 'Crop information',
                'verbose_name_plural': 'Crop information',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
            ],
            options={
                'verbose_name': 'Disease information',
                'verbose_name_plural': 'Disease information',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='agriculture.cropinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agriculture/disease-detections/')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('treatment', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('unavailable', 'Model unavailable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='agriculture.diseaseinformation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('observed_at', models.DateTimeField()),
                ('data_source', models.CharField(choices=[('sample', 'Development sample'), ('external_api', 'External API')], default='sample', max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='agriculture.cropinformation')),
            ],
            options={
                'ordering': ['-observed_at', 'crop__name'],
            },
        ),
    ]
