# Generated by Django 6.0.7 on 2026-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_ai_agriculture_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropinformation',
            name='locations',
            field=models.CharField(blank=True, help_text='Optional comma-separated regions.', max_length=255),
        ),
        migrations.AlterField(
            model_name='cropinformation',
            name='seasons',
            field=models.CharField(help_text='Comma-separated seasons (e.g. Kharif, Rabi, Summer).', max_length=255),
        ),
    ]
