# Generated by Django 6.0.7 on 2026-09-07 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200, verbose_name='Farm/Business Name')),
                ('provider_type', models.CharField(blank=True, default='Plant Nursery', max_length=100, verbose_name='Type of Provider')),
                ('description', models.TextField(blank=True, verbose_name='Short Description / Products Overview')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Personal / Residential Address')),
                ('farm_address', models.TextField(blank=True, verbose_name='Farm / Facility Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('state', models.CharField(blank=True, default='Kerala', max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=20, verbose_name='Pincode')),
                ('experience_years', models.CharField(blank=True, max_length=50, verbose_name='Years of Experience')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License / Registration Number')),
                ('license_type', models.CharField(blank=True, max_length=100, verbose_name='License Type')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, verbose_name='Issuing Authority')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='License Document')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Verification Status')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=200, verbose_name='Product Name')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Product Name (Alt)')),
                ('category_name', models.CharField(blank=True, default='Seeds', max_length=50, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description & Variety Notes')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='Quantity Available')),
                ('expected_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Expected Unit Price (₹)')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Set by Admin when approving.', max_digits=10, null=True, verbose_name='Marketplace Selling Price (₹)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='provider_items/', verbose_name='Product Image')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL (Optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Listed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Feedback')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Product Request',
                'verbose_name_plural': 'Provider Product Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_quantity', models.PositiveIntegerField(default=1)),
                ('unit_procurement_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='marketplace.product')),
            ],
        ),
    ]
