# Generated by Django 5.2.9 on 2026-08-19 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(help_text='Farm, Nursery, or Business Name', max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('pin_code', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_quantity', models.PositiveIntegerField()),
                ('unit_procurement_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_link', to='marketplace.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the seed, plant, or agricultural item', max_length=200)),
                ('description', models.TextField(help_text='Variety details, growing requirements, and features')),
                ('quantity', models.PositiveIntegerField(help_text='Units/Packets available')),
                ('expected_price', models.DecimalField(decimal_places=2, help_text='Expected procurement price per unit in INR', max_digits=10)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Admin-determined marketplace selling price', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='provider_requests/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Listed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin feedback or internal notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason given if request is rejected')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_requests', to='marketplace.category')),
                ('created_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='marketplace.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
