# Generated by Django 6.0 on 2026-09-03 03:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_provider'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Provider Profile', 'verbose_name_plural': 'Provider Profiles'},
        ),
        migrations.AlterModelOptions(
            name='providerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Provider Product Request', 'verbose_name_plural': 'Provider Product Requests'},
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='experience_years',
            field=models.CharField(blank=True, max_length=50, verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='farm_name',
            field=models.CharField(default='My Farm', max_length=200, verbose_name='Farm/Business Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='License Document'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='License Number'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='license_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='License Type'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider_type',
            field=models.CharField(blank=True, default='Plant Nursery & Seeds', max_length=100, verbose_name='Type of Provider'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin Feedback'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='category',
            field=models.CharField(choices=[('Seeds', '🌱 Seeds'), ('Plants', '🌿 Plants')], default='Seeds', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='created_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description & Variety Notes'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_items/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL (Optional)'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by Admin when approving.', max_digits=10, null=True, verbose_name='Marketplace Selling Price (₹)'),
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='providerrequest',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Unit Price (₹)'),
        ),
        migrations.AlterField(
            model_name='providerrequest',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='providerrequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='providers.providerprofile'),
        ),
        migrations.AlterField(
            model_name='providerrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantity Available'),
        ),
        migrations.AlterField(
            model_name='providerrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved & Listed'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
