# Generated by Django 6.0 on 2026-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_providerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='farm_address',
            field=models.TextField(blank=True, verbose_name='Farm / Facility Address'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='Issuing Authority'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Personal / Residential Address'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Short Description / Products Overview'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='License / Registration Number'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='provider_type',
            field=models.CharField(blank=True, default='Plant Nursery', max_length=100, verbose_name='Type of Provider'),
        ),
    ]
